### ISSUE TITLE
对高分辨率的电脑支持不友好

### ISSUE THREAD

**Issue by Monster-DP** [s337443501/NeteaseMusicCloudMatch#1]
![image](https://user-images.githubusercontent.com/47738288/134998949-7ff77cbc-d206-4a9f-8554-f2aba567c511.png)

**Comment by s337443501** [comment]
把缩放比例改成100%就好了

**Comment by s337443501** [comment]
新版本的已经对DPI缩放比例问题适配了

下载地址：https://github.com/s337443501/NeteaseMusicCloudMatch/releases
