### ISSUE TITLE
报个bug(无法记住登录状态)

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [s337443501/NeteaseMusicCloudMatch#13]
登录之后可用，但一旦退出后再打开必报错
![image](https://user-images.githubusercontent.com/87939280/184601267-44f59edf-851c-41c8-869a-c6098003021e.png)
重新扫码登录后又恢复正常，退出后再打开bug复现(已反复测试过)
看了一下Config好像是没有正确保存到cookie吧(可能和网易的一些改动有关)
![image](https://user-images.githubusercontent.com/87939280/184602181-09f79573-9310-4a87-8988-3a611bf77d75.png)
(图片是我手动打码,不是截屏问题)
希望大佬有时间修一下,每次都要重新扫码登录还是太麻烦了,万分感谢(=・ω・=)

**Comment by s337443501** [comment]
这应该是你的Cookie失效了导致的吧

**Comment by YaeSakuraQvQ** [comment]
> 这应该是你的Cookie失效了导致的吧

不是吧...我已经多次测试过了 扫码登陆→能正常使用→退出→再次打开报错
即使扫码登录后关了后立刻再打开也会报错无法正常自动登录
cookie失效一般也有个时间啊...感觉应该是bug吧

**Comment by s337443501** [comment]
> 要是有记忆登录就好了，感觉软件会更好用

那个自动登录你猜猜是干啥的

**Comment by CheongSzesuen** [comment]
> > 要是有记忆登录就好了，感觉软件会更好用
> 
> 那个自动登录你猜猜是干啥的

啊，我用的那个我退出再进就没了emmm（作者回复真快）

**Comment by CheongSzesuen** [comment]
> > 要是有记忆登录就好了，感觉软件会更好用
> 
> 那个自动登录你猜猜是干啥的

啊艹对不起我用的那个版本没自动登录emmm刚下了个github的看看https://www.52pojie.cn/thread-1520476-1-1.html这个上边的没记忆登录emm

**Comment by YaeSakuraQvQ** [comment]
我之前就找到解决方法了，打开config后把多余的行删掉就好了 每种类型只留一个 再次打开软件就可以自动登录了
还是不行的话就用浏览器登录网易云网页端，获取music_u啥的自己手填一下
如果有朋友出现相同的bug可以试试
(主要是很迷，最早是可以正常用的，出现bug后我先试过删掉重下啥的或者退出重登 bug还是反复出现...)
作者如果无法复现bug的话就当我自己人品问题...
