### ISSUE TITLE
被下架歌曲尽管获取到了ID也无法进行“匹配纠正”

### ISSUE THREAD

**Issue by gatterkwok** [s337443501/NeteaseMusicCloudMatch#18]
![image](https://github.com/s337443501/NeteaseMusicCloudMatch/assets/72333716/046029b4-7adb-4bd4-a6e6-ac074d11436c)
如图，此歌曲（C-BLOCK《小蜜蜂》）链接理应为https://music.163.com/#/song?id=455345089
但输入歌曲ID后点击“匹配纠正”却显示“输入的歌曲ID不存在”
其他被下架歌曲，例如DIGI GHETTO的《江浙HOOD》，通过推断得到准确的歌曲ID后，进行“匹配纠正”，依然会显示“输入的歌曲ID不存在”

感谢，麻烦大大了。

**Comment by s337443501** [comment]
这不是软件的问题，是官方不支持，我们也没办法

**Comment by gatterkwok** [comment]
> 这不是软件的问题，是官方不支持，我们也没办法

![image](https://github.com/s337443501/NeteaseMusicCloudMatch/assets/72333716/4a26eb3c-8c7d-44f3-bcc9-56110727a7d8)
那请大大删除这条“常见问题”，或者另行注明，
谢谢大大。

**Comment by s337443501** [comment]
这条说明没有问题，“下架”不等于被官方“删除”，“下架”的歌曲ID和链接还是存在的，链接是可以正常访问的，“删除”的歌曲即使是有ID，链接也访问不了，提示404

**Comment by gatterkwok** [comment]
> 这条说明没有问题，“下架”不等于被官方“删除”，“下架”的歌曲ID和链接还是存在的，链接是可以正常访问的，“删除”的歌曲即使是有ID，链接也访问不了，提示404

大大你好，
这条说明可能会让人觉得已下架歌曲的云盘匹配可通过此软件进行实现，从而造成误导。

**Comment by gatterkwok** [comment]
> 这条说明没有问题，“下架”不等于被官方“删除”，“下架”的歌曲ID和链接还是存在的，链接是可以正常访问的，“删除”的歌曲即使是有ID，链接也访问不了，提示404

抱歉，明白了，是我理解有误。
感谢大大。
