### ISSUE TITLE
打开扫码就闪退，能添加其他方式登录吗？

### ISSUE THREAD

**Issue by mjyhj** [s337443501/NeteaseMusicCloudMatch#4]

**Comment by s337443501** [comment]
哪里闪退？我怎么没遇到过，刚测试了一下，没有任何问题

**Comment by s337443501** [comment]
> > 哪里闪退？我怎么没遇到过，刚测试了一下，没有任何问题
> 
> 我是说网易云音乐 这个APP 闪退，我也不知道为什么，一点那个扫码，APP就闪退了

这个不应该是去找网易云音乐吗？找我们有什么用？
